### ISSUE TITLE
adding command aliases of kubectl and helm for .zshrc 

### ISSUE THREAD

**Issue by KiranSatyaRaj** [devtron-labs/utilities#16]
In utilities for [setup and installing microk8s](https://github.com/devtron-labs/utilities/blob/main/microk8s/microk8s-with-devtron.md), adding command aliases of kubectl and helm to .zshrc for zshell.

**Comment by verma-kunal** [comment]
Hey @KiranSatyaRaj , thanks for raising the issue!
IMO folks would be able to see and change their choice of shell, while using these two commands (which are being referred to).

So, don't think there would be a need to explicitly add another kind of shell. 

Would love to hear thoughts from the community as well

**Comment by KiranSatyaRaj** [comment]
Hey @verma-kunal, you're right, I should've thought this through, if folks working on shell other than bash, most probrably they would know to which .shellrc file to add these aliases, but how about adding/reminding them with a comment, when they are executing the commands for microk8s setup?

**Comment by Abhinav-26** [comment]
Hey @KiranSatyaRaj 
I think that won't be required as you mentioned users would already be aware of the shell they are using right?

Also, this repository is not participating in hacktoberfest so maybe you wanna try out some other ways to [contribute to Devtron](https://github.com/devtron-labs/hacktoberfest2022)? 

Please feel free to reach out to me or anyone in the [discord](https://discord.devtron.ai/) for any questions.
Looking forward to have your contributions.

**Comment by KiranSatyaRaj** [comment]
Thanks for taking time to clear this out @Abhinav-26, I'll be contributing to Devtron here onwards so it's okay if this repo is not a part of hacktoberfest I'm good with it and sure I'll definitely check out other ways as well, looking forward to learn more from the community, I'll close this issue then.
